name: 'bdt_adventureworks' 
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "dbt_packages"

models:
  bdt_adventureworks: 
    marts:
      +materialized: table
    staging:
      +materialized: view

seeds:
  bdt_adventureworks: 
    sap_adventure_works:
      +schema: sap_adw